name: Pipeline

on:
  push:
    branches: [main]
  # to run this workflow manually from the Actions tab
  workflow_dispatch:

# Test, Build and Deploy the app
jobs:
  test-build-node-js-app:
    uses: ./.github/workflows/node-js-tests.yml
    secrets:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
  test-build-python-package:
    uses: ./.github/workflows/python-tests.yml
  sync-to-deployment-fork:
    needs: [test-build-node-js-app, test-build-python-package]
    uses: ./.github/workflows/sync-to-deployment-fork.yml
    secrets:
      PAT: ${{ secrets.PAT }}
  sync-to-hugging-face-hub-spaces:
    needs: [test-build-node-js-app, test-build-python-package]
    uses: ./.github/workflows/sync-to-hugging-face-hub.yml
    secrets:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
