name: Sync to Deployment Fork
on:
  push:
    branches:
      - main
  # schedule:
  #  - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.9.0
        with:
          token: ${{ secrets.PAT }}
          owner: JTC-Smart-Retrieval
          repo: Smart-Retrieval-Deployment
          base: master
          head: master
          auto_approve: true
